### ISSUE TITLE
Monthly display: doubled entries for start and end date

### ISSUE THREAD

**Issue by steve-ks** [kanboard/plugin-calendar#4]
Hi there,
while trying out the calender plugin (which works mostly perfectly out of the box) we found several bugs. 

### Actual behaviour
Some dated kanban entries having both a starting and ending date are displayed either doubled (when having the same date) or with both a period over multiple dates till one before due day, then having the second date at due day. Also for one of both entries the time is displayed, for the other one not.

UPDATE: It seems that the displayed times are coming mostly from the created date, not from starting date. See attachments 2 & 3.

### Expected behaviour
It would be great having only a single entry, especially when both start and end date are set for the same day, and a time period going from start till end date for the whole entry instead of two calendar entries. Maybe the time could also be either displayed in one entry when within the same day or not at all. Could be a configurable.

### Steps to reproduce
Set a simple entry with start and end date. Best is to set it in the future for the same day. 

### Configuration

- Plugin version: 1.0.1
- Kanboard version: 5.6.30-0+deb8u1
- Database type and version: MariaDB 
- PHP version: 5.6
- Server-OS: debian 8 armhf
- Browser: Vivaldi (Chrome) & Firefox

![bug-duplicate-entries](https://user-images.githubusercontent.com/25765482/27527436-fd5eeee4-5a4b-11e7-978d-0f98a66a4a33.png)
![test-entry](https://user-images.githubusercontent.com/25765482/27527814-c229a8f8-5a4d-11e7-8e75-361cc2899533.png)
![test-monthly-display](https://user-images.githubusercontent.com/25765482/27527822-c715ff7e-5a4d-11e7-9ba7-6afac5f8d5f3.png)

**Comment by Biniou180** [comment]
Hi @steve-ks , as I was passing by I see your issue: the doubled entry is the due date when there is one (as you mentionned). An issue has already been opened previously about this (not closed yet): #3 which refers to [#2715](https://github.com/kanboard/kanboard/issues/2715) (before calendar was converted to an extension)

**Comment by steve-ks** [comment]
I see, thank you for your confirmation. So we are considering this as actively open. We are currently also from time to time working on extensions and plugins for kanboard but have not yet been to the calendar plugin. Maybe we also will work on another solution, not clear yet, but if we have some ideas of how to solve this issue we could post it as well. 

Regards,
Steve

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
