### ISSUE TITLE
Weekly display: Entries are displayed wrongly and partly not modifyable

### ISSUE THREAD

**Issue by steve-ks** [kanboard/plugin-calendar#5]
Hi there,
I try to split the issues up, but it might be that this one is related to issue #4. I am not directly sure if this one is a separate issues.

### Actual behaviour
When creating an entry with start and end date for a single day (say from 8am till 10am), the entry is displayed for the whole week as allday entry. Furthermore it is not possible to drag and drop the entry by its display down on the completely filled daily schedule (which should not be there anyways) but only by it's upper allday entry. 

### Expected behaviour
The entry should be displayed in the set time from 8 to 10 and not at all in the previous days. The entry should also not be displayed as allday entry in the upper row. And even when displaying it should be dragable everywhere.

### Steps to reproduce
Set an entry for the same day with start and ending date. Best not to use the first day of the week. Then look it up within the weekly calendar display.

### Configuration

- Plugin version: 1.0.1
- Kanboard version: 5.6.30-0+deb8u1
- Database type and version: MariaDB
- PHP version: 5.6
- Server-OS: debian 8 armhf
- Browser: Vivaldi (Chrome) & Firefox

![weekdisplay-setting](https://user-images.githubusercontent.com/25765482/27528435-a5f14fbc-5a50-11e7-8634-d0f8e27cbca4.png)

Displaying the entry in the week-calendar:
![weekdisplay-calendar](https://user-images.githubusercontent.com/25765482/27528445-ab374d28-5a50-11e7-8788-f3612e56854a.png)

After dragging and dropping the entry within the week-calendar the display totally changed but is still not correct:
![weekdisplay-after-dragging](https://user-images.githubusercontent.com/25765482/27528476-ce495630-5a50-11e7-81d5-b20f90df5394.png)

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
