### ISSUE TITLE
[monthly view] tasks not displayed when due date not in current month

### ISSUE THREAD

**Issue by Biniou180** [kanboard/plugin-calendar#7]
### Actual behaviour

When creating a task with a start date and a due date with more than one month between them, on calendar view the task is displayed only the month of due date. (please see example in "Steps to reproduce" part)

### Expected behaviour

The task should be displayed from the starting date (i.e. a task from march to may should be displayed on march + april + may view)

### Steps to reproduce

Create a task with a start date (let's say august, 7th 2017) and a due date next month (september, 12th 2017).
For the example, I created two tasks: 
![](https://framapic.org/vwGgBLygMBxb/NCKLImHQVsDv)
![](https://framapic.org/UcVAytpQ0UQV/rUGc9ZO0cRUB)

Display the calendar in august:
![](https://framapic.org/LEFyADzJRIxL/rVRIBOHcQqTy)

Then in september: 
![](https://framapic.org/sEqVHoFDWQnA/Qx600cEEIIAZ)

Task "cas nominal" is displayed in the August + September view as September, 10th is included in both views.
However, the other task is displayed only in September view despite its start date in August.

### Configuration

Tested on 
  * Framaboard (Kanboard 1.0.40, calendar included, sqlite 3.8.7.1) 
  * Kanboard 1.0.45 with calendar plugin 1.0.1, sqlite 3.19.3

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
